// Generated by CoffeeScript 1.6.3
var JadeCompiler, jade, progeny, sysPath, umd;

jade = require('jade');

sysPath = require('path');

umd = require('umd-wrapper');

progeny = require('progeny');

module.exports = JadeCompiler = (function() {
  JadeCompiler.prototype.brunchPlugin = true;

  JadeCompiler.prototype.type = 'template';

  JadeCompiler.prototype.extension = 'jade';

  function JadeCompiler(config) {
    this.config = config;
    this.getDependencies = progeny({
      rootPath: this.config.paths.root
    });
  }

  JadeCompiler.prototype.compile = function(data, path, callback) {
    var compiled, err, error, result, _ref, _ref1;
    try {
      compiled = jade.compile(data, {
        compileDebug: false,
        client: true,
        filename: path,
        pretty: !!((_ref = this.config.plugins) != null ? (_ref1 = _ref.jade) != null ? _ref1.pretty : void 0 : void 0)
      });
      return result = umd(compiled);
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  JadeCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'runtime.js')];

  return JadeCompiler;

})();
